# Generated by Django 5.0.6 on 2024-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
